### ISSUE TITLE
Missing library of subplot1

### ISSUE THREAD

**Issue by xldoooooo** [Junzeng-x14/Quadrotor_Load_Pulley#2]
There is an error about subplot1 in line 97 in main function.

**Comment by junzengx14** [comment]
Hello, do you have the library for `subplot1`?

**Comment by xldoooooo** [comment]
sorry, I don't have the library for subplot1

**Comment by junzengx14** [comment]
Check this [link](https://github.com/boriscc/matlab/blob/master/subplot1.m) out, I don't have code on my hand currently but you can google out some candidates of function subplot1.

**Comment by xldoooooo** [comment]
thanks a lot，I will try it



---Original---
From: "Jun ***@***.***&gt;
Date: Tue, May 24, 2022 11:11 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HybridRobotics/Quad-Load-Pulley] I met some error about subplot1in line 97 in main function (Issue #2)




 
Check this link out, I don't have code on my hand currently but you can google out some candidates of function subplot1.

**Comment by junzengx14** [comment]
Feel free to close this issue if it's resolved.

**Comment by xldoooooo** [comment]
ok



---Original---
From: "Jun ***@***.***&gt;
Date: Sun, May 29, 2022 13:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HybridRobotics/Quad-Load-Pulley] Error about subplot1 in line 97 in main function (Issue #2)




 
Feel free to close this issue if it's resolved.

**Comment by xldoooooo** [comment]
quite thanks

**Comment by xldoooooo** [comment]
surely not....



---Original---
From: "Jun ***@***.***&gt;
Date: Tue, May 24, 2022 10:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HybridRobotics/Quad-Load-Pulley] I met some error about subplot1in line 97 in main function (Issue #2)




 
Hello, do you have the library for subplot1?

**Comment by junzengx14** [comment]
^ Please don't spam in the discussion of the issue. Thanks.
